---
- name: This is a hello-next example
  hosts:  dckr-src-1
  tasks:
    - name: Copy file from remote file  '/srcjar/abc.txt' to local '/tmp/testnext.txt'.
      fetch:
        src: /srcjar/demo-0.0.1-SNAPSHOT.jar
        dest: /tmp/demo-0.0.1-SNAPSHOT.jar
        flat: yes
